version: "3.7"

services:
  app-server:
    build:
      context: newsapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/newsapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - newsapp-files:/_temp
    networks:
      - backend
      - frontend
  app-client:
    build:
      context: newsapp-react-client
      dockerfile: Dockerfile
      # args:
      # REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: newsapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:
  newsapp-files:

networks:
  backend:
  frontend:
