//export const BASE_URL = "http://192.168.99.100:8080/api";
export const BASE_URL = "http://localhost:8080/api";

export const GET_ERRORS = "GET_ERRORS";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const DELETE_POST = "DELETE_POST";

export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

export const DELETE_POST_IMAGE = "DELETE_POST_IMAGE";
export const DELETE_POST_VIDEO = "DELETE_POST_VIDEO";
export const UPLOAD_VIDEO_PROGRESS = "UPLOAD_VIDEO_PROGRESS";

export const GET_CURRENT_PERMISSIONS = "GET_CURRENT_PERMISSIONS";
export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const DELETE_ROLE = "DELETE_ROLE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERNAME_AVAILABILITY = "GET_USERNAME_AVAILABILITY";

export const GET_CURRENT_USER_AVATAR = "GET_CURRENT_USER_AVATAR";
export const DELETE_CURRENT_USER_AVATAR = "DELETE_CURRENT_USER_AVATAR";
export const GET_CURRENT_USER_PROFILE = "GET_CURRENT_USER_PROFILE";
export const GET_CURRENT_USER_ROLES = "GET_CURRENT_USER_ROLES";
export const GET_CURRENT_USER_PERMISSIONS = "GET_CURRENT_USER_PERMISSIONS";

export const GET_USER_PROFILES = "GET_USER_PROFILES";
export const GET_USER_AVATAR = "GET_USER_AVATAR";
export const DELETE_USER_AVATAR = "DELETE_USER_AVATAR";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_ROLES = "GET_USER_ROLES";




